In [4]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    6 non-null      int64
 1   age            3 non-null      float64
 2   city           4 non-null      object
 3   gender         6 non-null      object
 4   annual_income  6 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

In [18]:
df['age'].fillna(df['age'].mean())

0    25.000000
1    33.333333
2    35.000000
3    33.333333
4    33.333333
5    40.000000
Name: age, dtype: float64

In [27]:
df['city'].fillna(df['city'].mode()[0],inplace=True)

/tmp/ipykernel_4694/2972405200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna(df['city'].mode()[0],inplace=True)

In [28]:
df

   customer_id        age    city  gender  annual_income
0            1  25.000000  Mumbai    Male          40000
1            2  33.333333   Delhi  Female          80000
2            3  35.000000   Delhi  Female          60000
3            4  33.333333  Mumbai    Male         120000
4            2  33.333333   Delhi  Female          80000
5            5  40.000000   Delhi    Male          95000

In [35]:
df.drop_duplicates()
df

   customer_id        age    city  gender  annual_income
0            1  25.000000  Mumbai    Male          40000
1            2  33.333333   Delhi  Female          80000
2            3  35.000000   Delhi  Female          60000
3            4  33.333333  Mumbai    Male         120000
5            5  40.000000   Delhi    Male          95000

In [48]:
from sklearn.preprocessing import LabelEncoder


df_encoded = pd.get_dummies(df,columns=['city'])
hello=LabelEncoder()
df_encoded['gender']=hello.fit_transform(df_encoded['gender'])
df_encoded

   customer_id        age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.000000       1          40000       False         True
1            2  33.333333       0          80000        True        False
2            3  35.000000       0          60000        True        False
3            4  33.333333       1         120000       False         True
5            5  40.000000       1          95000        True        False

In [58]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_minmax = df_encoded.copy()
df_minmax[['age', 'annual_income']] = scaler.fit_transform(df_minmax[['age', 'annual_income']])
df_minmax

   customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000       False         True
1            2  0.555556       0         0.5000        True        False
2            3  0.666667       0         0.2500        True        False
3            4  0.555556       1         1.0000       False         True
5            5  1.000000       1         0.6875        True        False

In [66]:
from sklearn.preprocessing  import StandardScaler

scaler = StandardScaler()
df_standard[['age','annual_income']]=scaler.fit_transform(df_standard[['age','annual_income']])
df_standard

   customer_id           age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -1.725164e+00       1      -1.410970       False         True
1            2  3.108624e-16       0       0.036179        True        False
2            3  3.450328e-01       0      -0.687396        True        False
3            4  3.108624e-16       1       1.483328       False         True
5            5  1.380131e+00       1       0.578860        True        False

Min-Max Scaling → Use when data has a fixed range (like neural networks, image data). It keeps values between 0 and 1.
Standardisation → Use when data has outliers or normal distribution (like regression, SVM). It centers data around mean = 0.